# Generated by Django 2.2.3 on 2019-07-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
