# Generated by Django 2.2.3 on 2019-07-30 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20190730_2049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='description',
            field=models.TextField(blank=True, max_length=2500, null=True),
        ),
    ]
